package com.gestudio.crm.activity;

public enum ActivityType {
  EMAIL_DRAFTED,
  EMAIL_SENT_MANUALLY,
  EMAIL_SENT_BY_SYSTEM,
  EMAIL_RECEIVED,
  WHATSAPP_DRAFTED,
  WHATSAPP_SENT_MANUALLY,
  WHATSAPP_SENT_BY_SYSTEM,
  WHATSAPP_RECEIVED,
  PHONE_CALL,
  MEETING,
  DEMO,
  NOTE,
  STATUS_CHANGE,
  ASSIGNMENT_CHANGE,
  IMPORT,
  DUPLICATE_RESOLUTION,
  PROPOSAL_SENT,
  CUSTOM
}
