package com.gestudio.crm.exclusion;

public enum ExclusionReason {
  UNSUBSCRIBE_REQUEST,
  NEGATIVE_REPLY,
  PERMANENT_BOUNCE,
  INVALID_CONTACT,
  CLOSED_RELATIONSHIP,
  EXISTING_CUSTOMER,
  EXISTING_CONVERSATION,
  IRRELEVANT_INSTITUTION,
  MANUAL
}
